pipeline:
  build:
    image: busybox
    commands:
      - echo hi
  docker:
    debug: true
    repo: vespakoen/drone-docker-compose
    tag: development
    # email: k.schmeets@gmail.com
    # insecure: true
    # environment:
      # - DOCKER_LAUNCH_DEBUG="true"
