pipeline:
  build:
    image: busybox
    commands:
      - echo hi
  docker:
    debug: true
    repo: vespakoen/drone-docker-compose
    tag: development
    storage_driver: vfs
    insecure: true
    # environment:
      # - DOCKER_LAUNCH_DEBUG="true"
