workspace:
  base: /drone
  path: src/github.com/drone

pipeline:
  # build:
  #   image: busybox
  #   commands:
  #     - echo hi
  build:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone
    commands:
      - export PATH=$PATH:$GOPATH/bin
      - cd drone && pwd && make build
  docker:
    debug: true
    repo: vespakoen/drone
    tag: development
    storage_driver: vfs
    # insecure: true
