workspace:
  base: /drone
  path: src/github.com/drone

pipeline:
  # build:
  #   image: busybox
  #   commands:
  #     - echo hi
  build:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone
    commands:
      - export PATH=$PATH:$GOPATH/bin
      - cd drone
      - pwd
      - make deps
      - make gen
      - make build
  docker:
    debug: true
    repo: vespakoen/drone
    tag: development
    storage_driver: vfs
    # insecure: true
  build:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone-docker
    commands:
      - cd drone-docker
      - pwd
      - export PATH=$PATH:$GOPATH/bin
      - export GOOS=linux
      - export GOARCH=amd64
      - export CGO_ENABLED=0
      - go build -a -tags netgo
      - make docker
  docker:
    debug: true
    repo: vespakoen/drone-docker
    tag: development
    storage_driver: vfs
    # insecure: true
