workspace:
  base: /drone
  path: src/github.com/drone

pipeline:
  drone-build:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone
    commands:
      - export PATH=$PATH:$GOPATH/bin
      - cd drone
      - pwd
      - make deps
      - make gen
      - make build
  drone-publish:
    image: vespakoen/drone-docker:0.5.1
    debug: true
    repo: vespakoen/drone
    tag: ["latest", "0.5.1"]
    storage_driver: vfs
    context: drone
    dockerfile: drone/Dockerfile
    # insecure: true
  drone-docker-build:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone
    commands:
      - cd drone-docker
      - pwd
      - export PATH=$PATH:$GOPATH/bin
      - export GOOS=linux
      - export GOARCH=amd64
      - export CGO_ENABLED=0
      - make all
  drone-docker-docker:
    image: vespakoen/drone-docker:0.5.1
    debug: true
    repo: vespakoen/drone-docker
    tag: ["latest", "0.5.1"]
    storage_driver: vfs
    context: drone-docker
    dockerfile: drone-docker/Dockerfile
    # insecure: true
