workspace:
  base: /drone
  path: src/github.com/drone

pipeline:
  load-cache:
    image: plugins/sftp-cache:latest
    mount: /drone/docker
    restore: true
  drone-build:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone
    commands:
      - export PATH=$PATH:$GOPATH/bin
      - cd drone
      - pwd
      - make deps
      - make gen
      - make build
  drone-publish:
    image: vespakoen/drone-docker:0.5.1
    debug: true
    repo: vespakoen/drone
    tag: ["development"]
    storage_driver: vfs
    context: drone
    dockerfile: drone/Dockerfile
  # brads-drone-build:
  #   image: drone/golang:1.5
  #   environment:
  #     - GO15VENDOREXPERIMENT=1
  #     - GOPATH=/drone
  #   commands:
  #     - export PATH=$PATH:$GOPATH/bin
  #     - rm -rf drone
  #     - mv brads-drone drone
  #     - cd drone
  #     - pwd
  #     - make deps
  #     - make gen
  #     - make build
  # brads-drone-publish:
  #   image: vespakoen/drone-docker:0.5.1
  #   debug: true
  #   repo: vespakoen/brads-drone
  #   tag: ["development"]
  #   storage_driver: vfs
  #   context: drone
  #   dockerfile: drone/Dockerfile
  drone-docker-build:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
      - GOPATH=/drone
    commands:
      - cd drone-docker
      - pwd
      - export PATH=$PATH:$GOPATH/bin
      - export GOOS=linux
      - export GOARCH=amd64
      - export CGO_ENABLED=0
      - make all
  drone-docker-docker:
    image: vespakoen/drone-docker:0.5.1
    debug: true
    repo: vespakoen/drone-docker
    tag: ["development"]
    storage_driver: vfs
    context: drone-docker
    dockerfile: drone-docker/Dockerfile
  save-cache:
    image: plugins/sftp-cache:latest
    mount: /drone/docker
    rebuild: true
compose:
  cache:
    image: atmoz/sftp
    # ports:
    #   - "2222:22"
    volumes:
      - /cache:/home/cache/cache
    command: cache:cache:1001
