version: '2'
services:
  drone:
    image: drone/drone:0.5
    restart: always
    privileged: true
    environment:
      DRONE_GITHUB: "true"
      DRONE_GITHUB_CLIENT: $DRONE_GITHUB_CLIENT
      DRONE_GITHUB_SECRET: $DRONE_GITHUB_SECRET
      DRONE_AGENT_SECRET: $DRONE_AGENT_SECRET
      DRONE_ADMIN: vespakoen
      I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
      I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
      DRONE_DEBUG: "true"
    ports:
      - "8000:8000"
    volumes:
     - "/drone:/var/lib/drone"
     - "/var/run/docker.sock:/var/run/docker.sock"
  drone-agent:
    image: drone/agent:0.5
    restart: always
    privileged: true
    environment:
      DRONE_SERVER: http://drone:8000
      DRONE_SECRET: $DRONE_AGENT_SECRET
      DRONE_PLUGIN_PRIVILEGED: "true"
      DRONE_PLUGIN_NETRC: "true"
      I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
      I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
      DRONE_DEBUG: "true"
    links:
      - drone
  registry:
    image: registry:2.4.1
    environment:
      - "REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry"
    ports:
      - "5000:5000"
    volumes:
      - /registry/lib:/var/lib/registry
