version: '2'
services:
  drone:
    image: drone/drone:0.5
    restart: always
    environment:
      DRONE_GITHUB: "true"
      DRONE_GITHUB_CLIENT: fb09d223469748b46a33
      DRONE_GITHUB_SECRET: fc759d1c98f9722231f4f577fa0fcb66265fe003
      DRONE_AGENT_SECRET: 1n3iu23uihui23453632jn
      DRONE_ADMIN: vespakoen
      I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
      I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
      DRONE_DEBUG: "true"
    ports:
      - "8000:8000"
    volumes:
     - "/drone:/var/lib/drone"
  drone-agent:
    image: drone/agent:0.5
    restart: always
    environment:
      DRONE_SERVER: http://drone:8000
      DRONE_SECRET: 1n3iu23uihui23453632jn
      DRONE_DEBUG: "true"
      DRONE_PLUGIN_PRIVILEGED: "true"
      DRONE_PLUGIN_NETRC: "true"
      I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
      I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
    links:
      - drone
  registry:
    image: registry:2.4.1
    environment:
      - "REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry"
    ports:
      - "5000:5000"
    volumes:
      - /registry/lib:/var/lib/registry
