version: '2'
services:
  drone:
    image: vespakoen/drone:0.5.1
    # build:
    #   dockerfile: Dockerfile
    #   context: ./drone
    restart: always
    privileged: true
    environment:
      DRONE_GITHUB: "true"
      DRONE_GITHUB_CLIENT: $DRONE_GITHUB_CLIENT
      DRONE_GITHUB_SECRET: $DRONE_GITHUB_SECRET
      DRONE_AGENT_SECRET: $DRONE_AGENT_SECRET
      DRONE_ADMIN: vespakoen
      I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
      I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
      DRONE_DEBUG: "true"
    ports:
      - "8000:8000"
    volumes:
     - "/drone:/var/lib/drone"
     - "/var/run/docker.sock:/var/run/docker.sock"
    # networks:
    #   - drone
  drone-agent:
    image: vespakoen/drone:0.5.1
    restart: always
    environment:
      DRONE_SERVER: http://drone:8000
      DRONE_SECRET: $DRONE_AGENT_SECRET
      DRONE_TOKEN: $DRONE_USER_TOKEN
      DRONE_PLUGIN_NETRC: "true"
      I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: "true"
      I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: "true"
      DRONE_DEBUG: "true"
      # DRONE_PLUGIN_PULL: "false"
      DRONE_PLUGIN_PRIVILEGED: "plugins/docker,plugins/docker:*,vespakoen/drone-docker:*"
    links:
      - drone
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: agent
    # networks:
    #   - drone
  registry:
    image: registry:2.4.1
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_SECRET: $DOCKER_REGISTRY_HTTP_SECRET
    ports:
      - "5000:5000"
    volumes:
      - /registry/lib:/var/lib/registry
      - ./registry:/auth
    # networks:
    #   - drone
  cache:
    image: atmoz/sftp
    volumes:
      - /cache:/home/cache/cache
    command: cache:cache:1001
#     networks:
#       - drone

# networks:
#   drone:
#     external:
#       name: drone
